Implemented support for transferring money between End-User accounts including support for international remittance. The transfer component will automatically convert the amount transferred into the recipient's local currency based on the conversion rates supplied by the European Central Bank if money is transferred between users in 2 different countries. In order to support conversion between currencies a new field: symbol has been added to database table: System.Country_Tbl. The new field contains the old value from the currency field and the currency field now contains the ISO-4427 code for the country's currency. Additionally, a new account will automatically be created and the recipient notified if he / she doesn't already have an account.
Renamed method: valAmount to valPrice in class: Validate to specify that the method is validating a product price.
A new valAmount method has been added which validates the amount transferred between 2 end-user accounts.

git-svn-id: svn://svn.cellpointmobile.com/mpoint/server/trunk@72 86c063f6-31ef-4d33-b9ba-d2d3e4924f03